import { ROUTES, type TourRoute } from "./routes";
import type { Tour } from "./types";

/** The 24 tours from the prototype (`design-reference/kart.html` → TOURS).
 *
 *  Summit coordinates are now real: each one is resolved through Kartverket's
 *  place-name register, snapped to the highest cell of the 1 m terrain model and
 *  cross-checked against the published height. The teasers are still editorial
 *  drafts. In production these rows live in Supabase; this module is the seed
 *  and the local fallback.
 */
export const TOURS: Tour[] = [
  { slug: "storgalten", name: "Storgalten", region: "Lyngen", lat: 69.88543, lng: 20.25257, summitM: 1219, verticalM: 1219, duration: "5–7 t", grade: 3, aspect: "NV", season: "feb–mai", hasGuide: true, teaser: "Fjord-til-topp i ytre Lyngen: 1219 høydemeter rett opp fra havnivå." },
  { slug: "store-skalltinden", name: "Store Skalltinden", region: "Troms", lat: 69.87096, lng: 19.29283, summitM: 901, verticalM: 980, duration: "4–6 t", grade: 3, aspect: "SØ", season: "jan–mai", hasGuide: true, teaser: "980 høydemeter fra havet i Glimbukta: opp forbi Skallvatnet på 320, den kuperte ryggen vestover — og de siste 800 metrene mot toppen med bratt terreng på begge sider." },
  { slug: "store-blamann", name: "Store Blåmann", region: "Troms", lat: 69.73502, lng: 18.59147, summitM: 1044, verticalM: 1040, duration: "4–6 t", grade: 3, aspect: "S", season: "feb–mai", hasGuide: true, teaser: "Kvaløyas brattest profilerte klassiker — krever stabile forhold og god planlegging." },
  { slug: "kjolen", name: "Kjølen", region: "Troms", lat: 69.73349, lng: 18.78773, summitM: 790, verticalM: 580, duration: "3–5 t", grade: 1, aspect: "NØ", season: "nov–mai", hasGuide: true, teaser: "580 høydemeter fra Finnvikvatnet innover dalen til radaren og varmebua — en av Kvaløyas mest besøkte topper." },
  { slug: "rodtinden", name: "Rødtinden", region: "Troms", lat: 69.70147, lng: 18.75254, summitM: 470, verticalM: 450, duration: "2–4 t", grade: 1, aspect: "SØ", season: "des–mai", hasGuide: true, teaser: "450 høydemeter fra Storelva skistadion opp den åpne sørøstsida — den mest besøkte toppen rundt Tromsø." },
  { slug: "storfjellet", name: "Storfjellet", region: "Troms", lat: 69.6491, lng: 19.39317, summitM: 1088, verticalM: 1050, duration: "4–6 t", grade: 3, aspect: "SØ", season: "jan–mai", hasGuide: true, teaser: "1050 høydemeter rett opp fra Breivikeidet: langs elvedalen mot Russevankskardet, opp på sørryggen på rundt 400 — og ryggen til topps med det bratteste mellom 950 og 1040." },
  { slug: "skarlitinden", name: "Skarlitinden", region: "Troms", lat: 69.63305, lng: 19.33467, summitM: 858, verticalM: 940, duration: "4–6 t", grade: 2, aspect: "N", season: "jan–mai", hasGuide: true, teaser: "940 høydemeter fra Sandeggen på Breivikeidet: langs Russevankelva inn i Russevankskaret, sving mot sør-søraust ved punkt 511 — og et langt toppplatå til varden med rennene under." },
  { slug: "fastdalstinden", name: "Fastdalstinden", region: "Lyngen", lat: 69.62935, lng: 20.16792, summitM: 1275, verticalM: 1270, duration: "6–8 t", grade: 3, aspect: "SØ", season: "jan–mai", hasGuide: true, teaser: "1270 høgdemeter frå vegenden på Varto: anleggsvegen til dammen, på land rundt det regulerte Rottenvikvatnet, flata på 650 og ryggen rett mot toppen." },
  { slug: "tromsdalstinden", name: "Tromsdalstinden", region: "Troms", lat: 69.6071, lng: 19.14585, summitM: 1238, verticalM: 1212, duration: "5–7 t", grade: 2, aspect: "V", season: "des–mai", hasGuide: true, teaser: "Tromsøs signaturtopp: lang, jevn oppstigning fra Tromsdalen med storslått utsikt mot Lyngen." },
  { slug: "gabrielfjellet", name: "Gabrielfjellet", region: "Troms", lat: 69.57821, lng: 19.37987, summitM: 1214, verticalM: 1140, duration: "4–6 t", grade: 3, aspect: "N", season: "des–mai", hasGuide: true, teaser: "1140 høydemeter fra Stormo ved fv. 91: glissen skog sørover, rullende rygger fra 400 til 850 — og store flak helt til varden på fjellet registeret kaller Iverfjellet." },
  { slug: "rornestinden", name: "Rørnestinden", region: "Lyngen", lat: 69.57329, lng: 20.11187, summitM: 1030, verticalM: 1018, duration: "4–6 t", grade: 2, aspect: "V", season: "jan–mai", hasGuide: true, teaser: "Den vennligste inngangen til Lyngsalpene, med slak rygg og romslig nedkjøring." },
  { slug: "hamperokken", name: "Hamperokken", region: "Troms", lat: 69.5621, lng: 19.35872, summitM: 1397, verticalM: 1389, duration: "5–7 t", grade: 4, aspect: "NV", season: "feb–mai", hasGuide: true, teaser: "1400 høydemeter fra Fv91, men skiene settes igjen på Middagsaksla 1076 moh – siste 1,4 km er eksponert rygg til fots." },
  { slug: "kavringtinden", name: "Kavringtinden", region: "Lyngen", lat: 69.54704, lng: 20.12428, summitM: 1289, verticalM: 1250, duration: "5–7 t", grade: 3, aspect: "N", season: "mar–mai", hasGuide: true, teaser: "Indre Lyngen-perle med nordvendt snø som holder seg langt ut i mai." },
  { slug: "fagerfjellet", name: "Fagerfjellet", region: "Troms", lat: 69.54528, lng: 19.27811, summitM: 957, verticalM: 950, duration: "4–6 t", grade: 2, aspect: "V", season: "nov–mai", hasGuide: true, teaser: "950 høydemeter fra skolen på Fagernes: dyrka mark, skogen mot punkt 459 og søkket austover til varden på 871 der de fleste snur — toppen ligger et småkupert stykke lenger inn." },
  { slug: "hesten-segla", name: "Hesten (Segla)", region: "Senja", lat: 69.51388, lng: 17.58462, summitM: 556, verticalM: 510, duration: "2–4 t", grade: 2, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "Kort tur, stort postkort: nedkjøring med Segla i fanget og havet under." },
  { slug: "keipen", name: "Keipen", region: "Senja", lat: 69.4953, lng: 17.72324, summitM: 938, verticalM: 840, duration: "3–5 t", grade: 3, aspect: "S", season: "jan–mai", hasGuide: true, teaser: "840 høydemeter fra Medfjordbotnvatnan gjennom skåla sør for toppen; ruta skrår opp, mens fallinja ved sida av måler 38–52 grader." },
  { slug: "husfjellet", name: "Husfjellet", region: "Senja", lat: 69.4696, lng: 17.27193, summitM: 632, verticalM: 640, duration: "3–5 t", grade: 1, aspect: "SØ", season: "feb–mai", hasGuide: true, teaser: "640 høgdemeter frå kyrkja på Skaland: Dronningstien til Grillbua, skogstraséen opp Sommerdalen og ryggen over Sommerdalhaugen — mest utsikt for minst innsats, seier kjelda." },
  { slug: "breitinden", name: "Breitinden", region: "Senja", lat: 69.45168, lng: 17.65623, summitM: 1007, verticalM: 1050, duration: "4–6 t", grade: 4, aspect: "SV", season: "jan–apr", hasGuide: true, teaser: "1050 høydemeter fra Svarthola via Svartholvatnet og nordbredden av Breitindvatnet; de siste 244 er klyving på sørvestryggen." },
  { slug: "skolpan", name: "Skolpan", region: "Senja", lat: 69.40894, lng: 17.45379, summitM: 777, verticalM: 610, duration: "2–4 t", grade: 1, aspect: "S", season: "feb–mai", hasGuide: true, teaser: "607 høgdemeter frå fv. 862 i Krokelvdalen: jamt stigande gjennom småskogen, over flata på 465 moh og nordvestover inn på ryggen til Skolpan." },
  { slug: "tredje-svanfjell", name: "Tredje Svanfjell", region: "Senja", lat: 69.29949, lng: 17.40362, summitM: 899, verticalM: 660, duration: "3–5 t", grade: 2, aspect: "V", season: "des–mai", hasGuide: true, teaser: "660 høgdemeter rett frå parkeringslomma i Kaperdalen: skaret nord for punkt 504, jamt opp til fortoppen på 870, og dei siste 36 metrane til klassikaren på Senja." },
  { slug: "lonketind", name: "Lonketinden", region: "Senja", lat: 69.09401, lng: 16.9161, summitM: 845, verticalM: 780, duration: "3–5 t", grade: 2, aspect: "S", season: "feb–mai", hasGuide: true, teaser: "784 høgdemeter frå vassbassenget ved Finnelva: det flate myrterrenget, ryggen mot Lonketuva og toppryggen som gradvis blir brattare til Senjas Lonketinden." },
  { slug: "hattfjellet", name: "Hattfjellet", region: "Harstad", lat: 68.97467, lng: 16.32649, summitM: 857, verticalM: 830, duration: "3–5 t", grade: 3, aspect: "S", season: "feb–apr", hasGuide: true, teaser: "830 høydemeter fra Grøtavær: traktorveien opp Bjørndalen, venstre der det flater — og sørsida til topps, med utsikt mot Andøya fra øyas ytterste tur." },
  { slug: "stortussen", name: "Stortussen", region: "Harstad", lat: 68.97434, lng: 16.36664, summitM: 945, verticalM: 1020, duration: "4–6 t", grade: 3, aspect: "S", season: "feb–apr", hasGuide: true, teaser: "1020 høydemeter fra Dale: sommerstien til Storvatnet og Trollvatnet, det slakeste terrenget opp — og ryggen nordover til toppen, der ski kan settes igjen før det siste støtet." },
  { slug: "litletussen", name: "Litletussen", region: "Harstad", lat: 68.96367, lng: 16.40377, summitM: 795, verticalM: 760, duration: "3–5 t", grade: 3, aspect: "SØ", season: "feb–apr", hasGuide: true, teaser: "760 høydemeter fra Dale: sommerstien mot Storvatnet, rundt vatnet på land — og glissen skog nordaust til sørryggen, den slakeste inngangen til toppen." },
  { slug: "slattheia", name: "Slåttheia", region: "Harstad", lat: 68.95164, lng: 16.3404, summitM: 694, verticalM: 640, duration: "2–4 t", grade: 2, aspect: "SØ", season: "feb–apr", hasGuide: true, teaser: "640 høydemeter fra Dale: sommerstien mot Storvatnet, forbi 342-høgda — og den store søraustvendte lia til topps, utenom det meste av skredterrenget. Grytøyas innsteg." },
  { slug: "istinden", name: "Vestre Istinden", region: "Troms", lat: 68.94986, lng: 18.5668, summitM: 1489, verticalM: 1430, duration: "5–7 t", grade: 3, aspect: "NV", season: "feb–mai", hasGuide: true, teaser: "1432 høgdemeter frå Tindelva ved Iselvmoen: den bratte bjørkelia, inn i gryta under nordveggen, og opp ryggen vest for breen til det høgaste av Istindan." },
  { slug: "skjellesvikgalten", name: "Skjellesvikgalten", region: "Harstad", lat: 68.92499, lng: 16.54688, summitM: 987, verticalM: 1020, duration: "4–6 t", grade: 4, aspect: "Ø", season: "feb–apr", hasGuide: true, teaser: "1020 høydemeter fra Skjellesvika: traktorvegen fra havna og den store slake austryggen vestover — til toppen kilden kaller 800 og registeret måler 987." },
  { slug: "nona", name: "Nona", region: "Harstad", lat: 68.92158, lng: 16.45062, summitM: 1009, verticalM: 1020, duration: "4–6 t", grade: 4, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "1020 høydemeter fra Dale: skitursporet innover Dalsdalen, over Dalselva — og den breieste renna til Grytøyas høyeste, 30–45 grader sammenhengende med øks og stegjern i sekken." },
  { slug: "trolltinden", name: "Trolltinden", region: "Harstad", lat: 68.91391, lng: 16.48921, summitM: 918, verticalM: 940, duration: "4–6 t", grade: 3, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "940 høydemeter fra ferjeleiet på Bjørnerå: slake Bjørnrådalen mellom bratte vegger, ryggen til skulderen — og toppstøtet til fots, med skavler å passe." },
  { slug: "arbostadtinden", name: "Årbostadtinden", region: "Harstad", lat: 68.90861, lng: 17.3481, summitM: 1179, verticalM: 1170, duration: "4–6 t", grade: 4, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "1170 høgdemeter på fire kilometer frå fv. 7804: traktorvegen sørover frå den gamle skolen, vest for Storelva til flata ved hytta — og skrårenna som er landemerket, 30–40 grader heilt til varden." },
  { slug: "klaptinden", name: "Klåptinden", region: "Harstad", lat: 68.9085, lng: 17.27856, summitM: 998, verticalM: 840, duration: "3–5 t", grade: 3, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "840 høydemeter fra Himmelberget: opp fra Klåpvatnet på sommerruta — steinete under skogen, avblåst over — og ryggen til topps, med kjøring på 20–30 grader hjem." },
  { slug: "toppen", name: "Toppen", region: "Harstad", lat: 68.90812, lng: 16.40556, summitM: 759, verticalM: 720, duration: "3–5 t", grade: 4, aspect: "Ø", season: "feb–apr", hasGuide: true, teaser: "720 høydemeter fra Toppentunnelen: austsida av Hallevikelva, sør for Toppskarvatnet på land — og ryggen sørover til Toppen, fjellet som ga tunnelen navn." },
  { slug: "lundenesgalten", name: "Lundenesgalten", region: "Harstad", lat: 68.90377, lng: 16.53122, summitM: 787, verticalM: 790, duration: "3–5 t", grade: 3, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "790 høgdemeter frå Lundenes kirke: traktorvegen langs Forselva til Storskogbakkan, og så heile den store sørsida — samanhengande 25–35 grader, fjellet halve Harstad ser på." },
  { slug: "middagstinden-andorja", name: "Middagstinden på Andørja", region: "Harstad", lat: 68.88625, lng: 17.15247, summitM: 630, verticalM: 620, duration: "2–4 t", grade: 2, aspect: "NØ", season: "feb–apr", hasGuide: true, teaser: "620 høydemeter fra Slettneset: sommerruta sørover, opp langs Mølnelva utenom de bratte partiene — og ryggen nord for toppen. Kort tur, men kilden er tydelig: det har gått skred på alle nedkjøringene." },
  { slug: "skartinden", name: "Skartinden", region: "Harstad", lat: 68.87745, lng: 17.33598, summitM: 1149, verticalM: 1290, duration: "5–7 t", grade: 4, aspect: "V", season: "jan–apr", hasGuide: true, teaser: "1290 høydemeter fra Vang: elvedalen til Ytterholla, skardet mellom Vasskartinden og Skartinden — og flata austover til toppen, med 60-graders klipper å styre unna i nedkjøringa." },
  { slug: "langlitinden", name: "Langlitinden", region: "Harstad", lat: 68.86785, lng: 17.38742, summitM: 1276, verticalM: 1300, duration: "5–7 t", grade: 4, aspect: "V", season: "jan–apr", hasGuide: true, teaser: "1300 høydemeter fra snuplassen ved Vang til Nordens høyeste øytopp: sommerruta langs Bjørndalselva, flata med vatnet på land — og traversen på 800–900, partiet med skredhistorikk, før toppflanken." },
  { slug: "krakrotinden", name: "Kråkrøtinden", region: "Harstad", lat: 68.86266, lng: 17.40083, summitM: 1186, verticalM: 1190, duration: "5–7 t", grade: 4, aspect: "N", season: "feb–apr", hasGuide: true, teaser: "1190 høydemeter fra Fornes: dalen mot Blåisen, morenen sør for isen — og 40-graderspassasjen til toppen, med øks og stegjern i sekken." },
  { slug: "ristinden", name: "Ristinden", region: "Harstad", lat: 68.84241, lng: 17.25256, summitM: 1056, verticalM: 1050, duration: "4–6 t", grade: 4, aspect: "SV", season: "feb–apr", hasGuide: true, teaser: "1050 høydemeter fra skolen på Ånstad: lia og myrene til Breilifatet — og rampa på sørvestsiden til toppen, der Johammarrenna og Risenrenna venter på stabile dager." },
  { slug: "snotinden", name: "Snøtinden", region: "Harstad", lat: 68.83669, lng: 17.30588, summitM: 1215, verticalM: 1240, duration: "5–7 t", grade: 4, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "1240 høydemeter fra Ånstad til Andørjas store klassiker: skogen aust for Snøfjellelva, Snøfjellvatnet og vestflanken — fem navngitte nedfarter, og øks og stegjern i sekken." },
  { slug: "storhornet-kvafjord", name: "Storhornet i Kvæfjord", region: "Harstad", lat: 68.8246, lng: 16.21309, summitM: 722, verticalM: 660, duration: "4–6 t", grade: 1, aspect: "S", season: "nov–apr", hasGuide: true, teaser: "660 høydemeter fra Kvæfjordeidet etter Harstads alltid best preparerte løype til Koven — og en slak, sørvendt rygg videre til varden. Solturen i rundelen." },
  { slug: "vetefjellet", name: "Vetefjellet", region: "Harstad", lat: 68.80013, lng: 16.34039, summitM: 547, verticalM: 390, duration: "2–4 t", grade: 2, aspect: "S", season: "feb–apr", hasGuide: true, teaser: "390 høgdemeter over Olaåsen: skogsvegen inn til traktorvegen, Helgevallan og høgde 361 i lett terreng — eit leikent skifjell med kort anmarsj og fin skogskjøring." },
  { slug: "storlitinden", name: "Storlitinden", region: "Harstad", lat: 68.79801, lng: 16.31034, summitM: 613, verticalM: 450, duration: "2–4 t", grade: 1, aspect: "S", season: "des–apr", hasGuide: true, teaser: "450 høgdemeter frå den brøyta parkeringa ved Kvæfjordløypene: traktorvegen forbi Kvilheim, vest for Reingjerdhågen og opp den jamne skråninga som òg er sommarruta — lett og sikker heile vegen." },
  { slug: "stortinden-rolla", name: "Stortinden på Rolla", region: "Harstad", lat: 68.79234, lng: 17.03681, summitM: 1020, verticalM: 980, duration: "5–7 t", grade: 4, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "980 høydemeter fra Indre Forså til Rollas høyeste: myrene, austsida av Mevatnet på land — og renna sør for toppen, jevnt 30–40 grader, med Drangen som ekspertkulisse." },
  { slug: "rundtind", name: "Rundtinden", region: "Harstad", lat: 68.77916, lng: 17.05198, summitM: 872, verticalM: 880, duration: "4–6 t", grade: 3, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "880 høgdemeter frå Holtet: traktorvegen opp til hyttefeltet ved Sandvatnet, rundt magasinet og over myrene til oppstigninga nordaust for Skavbakkan — den enklaste vegen opp på ein av Drangens toppar, med pinakkelen Tottålen på austsida." },
  { slug: "sula", name: "Sula", region: "Harstad", lat: 68.76819, lng: 17.05909, summitM: 848, verticalM: 830, duration: "3–5 t", grade: 2, aspect: "SØ", season: "feb–apr", hasGuide: true, teaser: "830 høydemeter fra Breivoll: den jevne traktorveien, opp Skogsheia der skogen tynnes — og nesten rett linje til M-fjellets topp, på heng som måler litt over 20 grader." },
  { slug: "heia", name: "Heia", region: "Harstad", lat: 68.75594, lng: 16.50177, summitM: 527, verticalM: 470, duration: "2–4 t", grade: 1, aspect: "Ø", season: "des–apr", hasGuide: true, teaser: "470 høgdemeter frå fotballbanen ved Krafthallen opp den gamle alpinbakken: myra, det opne feltet og Maistua på 321 — og ryggen over tregrensa. Harstads ettermiddagstur, med lys i bakken på kvardagskveldar." },
  { slug: "hinnstein", name: "Hinnstein", region: "Harstad", lat: 68.74726, lng: 16.50311, summitM: 560, verticalM: 510, duration: "2–4 t", grade: 3, aspect: "SØ", season: "jan–apr", hasGuide: true, teaser: "510 høgdemeter frå Breivikhaugen: skogsvegen grunneigarane bygde i 2016, forbi gapahuken og opp den gamle hoppbakken mellom Litle Hinnstein og Hinnstein — og stien opp sørvestsida, den slake sida av eit fjell som er avskore mot nordvest." },
  { slug: "lasselitinden", name: "Lasselitinden", region: "Harstad", lat: 68.74548, lng: 16.90057, summitM: 896, verticalM: 860, duration: "3–5 t", grade: 3, aspect: "S", season: "feb–apr", hasGuide: true, teaser: "860 høydemeter fra Storelvas utløp på fv. 848: opp lia til Rollryggen — og sørryggen til topps på 20–30 grader, med Djupedalens skavler som naboer du holder avstand til." },
  { slug: "hemmestadfjellet", name: "Hemmestadfjellet", region: "Harstad", lat: 68.71739, lng: 16.10727, summitM: 686, verticalM: 680, duration: "3–5 t", grade: 2, aspect: "N", season: "jan–apr", hasGuide: true, teaser: "680 høydemeter fra Vebbestadsætran: traktorveien gjennom granfeltet — og ryggen vest for Vebbestadvatnet til topps, jevn og lett kjøring som er fin for ferske." },
  { slug: "middagstinden-kvafjord", name: "Middagstinden i Kvæfjord", region: "Harstad", lat: 68.71035, lng: 16.15845, summitM: 922, verticalM: 910, duration: "4–6 t", grade: 4, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "910 høydemeter fra Hundstadsætran: traktorveien til Vebbestadvatnet, austover forbi den store steinen — og et toppparti på 45–50 grader, ofte hard skare, med øks og stegjern." },
  { slug: "nattmalsfjellet", name: "Nattmålsfjellet", region: "Harstad", lat: 68.70959, lng: 16.4571, summitM: 546, verticalM: 480, duration: "2–4 t", grade: 3, aspect: "N", season: "feb–apr", hasGuide: true, teaser: "480 høgdemeter frå Kilkam idrettsanlegg: skisporet forbi barnehagen, av sporet sørover på åsryggen — og slukta dei siste hundre metrane. Ser enkelt ut, men det har gått skred her." },
  { slug: "horntindan", name: "Horntindan", region: "Harstad", lat: 68.70296, lng: 16.09495, summitM: 911, verticalM: 930, duration: "4–6 t", grade: 4, aspect: "NV", season: "feb–apr", hasGuide: true, teaser: "930 høydemeter fra Skommesvik: opp mot Hemmestadfjellet og ryggen sørover til Horntindan — med normalnedkjøringa over Hornflata på 35–40 grader for stabile dager." },
  { slug: "tverrfjellet", name: "Tverrfjellet", region: "Harstad", lat: 68.70181, lng: 16.13535, summitM: 889, verticalM: 880, duration: "4–6 t", grade: 2, aspect: "S", season: "feb–apr", hasGuide: true, teaser: "880 høydemeter fra fjorden ved Melåa: traktorveien langs Melåelva, myrene ved kraftlinja, vest for Tverrelvfoten — og det åpne området rett opp mot toppen, med sørvendt kjøring på 15–25 grader hjem." },
  { slug: "spanstinden", name: "Spanstinden", region: "Narvik", lat: 68.69987, lng: 17.86829, summitM: 1457, verticalM: 1050, duration: "4–6 t", grade: 2, aspect: "SØ", season: "feb–jun", hasGuide: true, teaser: "1050 høydemeter fra Bukkemyrvatnet på Gratangsfjellet: terrassene mot Sølvfjellet, fonna sørøst for toppen — og de spektakulære siste meterne til varden." },
  { slug: "sorvikfjellet", name: "Sørvikfjellet", region: "Harstad", lat: 68.69461, lng: 16.47892, summitM: 607, verticalM: 560, duration: "2–4 t", grade: 4, aspect: "Ø", season: "jan–apr", hasGuide: true, teaser: "560 høgdemeter frå Kilbotnveien: avkjøringa på Nordvikmyra og rett inn mot toppvarden, i det enklaste terrenget litt sør for toppen — utanom henget nordaust der det går skred kvart år." },
  { slug: "melaaksla", name: "Melåaksla", region: "Harstad", lat: 68.63266, lng: 16.13919, summitM: 916, verticalM: 960, duration: "4–6 t", grade: 2, aspect: "N", season: "feb–apr", hasGuide: true, teaser: "960 høydemeter fra Melå: traktorveien til Dalbotnen, forbi hytta ved 505-høgda — og den lange ryggen sørover til toppen, med 15–25 graders kjøring hjem mot Austerfjorden." },
  { slug: "rundfjellet-harstad", name: "Rundfjellet i Harstad", region: "Harstad", lat: 68.63249, lng: 16.27351, summitM: 868, verticalM: 770, duration: "4–6 t", grade: 2, aspect: "NØ", season: "feb–apr", hasGuide: true, teaser: "770 høgdemeter og nesten sju kilometer frå DNT-hytta på Bjørnhaugen: vestsida av Storvatnet, bekkedalen nord for høyde 339 med skredterreng på begge sider — og nordaustryggen til topps i cruiseterreng." },
  { slug: "jakobstinden", name: "Jakobstinden", region: "Harstad", lat: 68.61628, lng: 16.18072, summitM: 976, verticalM: 1060, duration: "5–7 t", grade: 3, aspect: "SØ", season: "jan–apr", hasGuide: true, teaser: "1060 høydemeter fra samme Y-kryss som Kongsviktinden: fire kilometer innover Kongsvikdalen, myrene ved Sætran, den brede rampa — hold sør for skavlen — og det brede platået til toppen med pinakkelen." },
  { slug: "stortinden-sortland", name: "Stortinden i Sortland", region: "Vesterålen", lat: 68.60306, lng: 15.62987, summitM: 1020, verticalM: 1010, duration: "4–6 t", grade: 4, aspect: "V", season: "jan–apr", hasGuide: true, teaser: "1010 høgdemeter frå Vangpollen kraftstasjon: den bratte dalen som blir brattare og brattare, til høgre under bandet på 600 moh og opp ryggen — ein av Hinnøyas tusenmetringar, med bratt kjøring heilt ned til havet." },
  { slug: "haukebotinden", name: "Haukebøtinden", region: "Harstad", lat: 68.59662, lng: 16.39746, summitM: 905, verticalM: 860, duration: "4–6 t", grade: 2, aspect: "Ø", season: "des–apr", hasGuide: true, teaser: "860 høydemeter fra Gausvik kirke: over demningen, opp austsida av Heimetverrelva — og det minst krevjande terrenget rett mot toppen. Rundens korteste dag, med sesong fra desember." },
  { slug: "reinspalen", name: "Reinspælen", region: "Harstad", lat: 68.59341, lng: 15.69923, summitM: 1117, verticalM: 1400, duration: "6–8 t", grade: 4, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "1400 høydemeter fra Våtvoll til Kvæfjords høyeste — Kobberyggen og Geitryggen med mye opp og ned, og en eksponert ryggtravers med vegg på begge sider til slutt." },
  { slug: "satertinden", name: "Sætertinden", region: "Harstad", lat: 68.58656, lng: 16.36195, summitM: 1095, verticalM: 1110, duration: "5–7 t", grade: 2, aspect: "Ø", season: "feb–apr", hasGuide: true, teaser: "1110 høydemeter fra Sandtorg idrettsanlegg på Årbogen: traktorveien langs Årbogelva, sør for Årbogvatnet — og den staka østryggen forbi nødbua, med telefonstolpene som los mot toppen." },
  { slug: "kongsviktinden", name: "Kongsviktinden", region: "Harstad", lat: 68.58291, lng: 16.26536, summitM: 980, verticalM: 1090, duration: "6–8 t", grade: 3, aspect: "N", season: "jan–apr", hasGuide: true, teaser: "1090 høydemeter fra Y-krysset før bommen: den vinterstengte veien innover Kongsvikdalen, sommerstien ved Sætran og sørkonturen over platået — det slakeste terrenget mot den sørøstlige toppen, med øks og stegjern i sekken." },
  { slug: "snotinden-tjeldsund", name: "Snøtinden i Tjeldsund", region: "Harstad", lat: 68.56784, lng: 16.02992, summitM: 980, verticalM: 1020, duration: "4–6 t", grade: 2, aspect: "NØ", season: "feb–apr", hasGuide: true, teaser: "1020 høydemeter fra Dalelvas utløp i Fiskefjorden: traktorveien opp Norddalen, det langstrakte Marsslottfjellet — og ryggen sørvestover til toppen, med bare tre heng på rundt 25 grader i hele nedkjøringen." },
  { slug: "taraldsviktinden", name: "Taraldsviktinden", region: "Harstad", lat: 68.55162, lng: 16.16806, summitM: 776, verticalM: 780, duration: "3–5 t", grade: 3, aspect: "N", season: "feb–apr", hasGuide: true, teaser: "780 høydemeter fra fjæra innerst i Fiskefjorden: traktorveien øst for Gårdselva, mot Mølnskaret — og nordryggen til topps, med isøks og stegjern for ryggpartiet på 30 grader." },
  { slug: "nonstinden", name: "Nonstinden", region: "Harstad", lat: 68.54904, lng: 15.68189, summitM: 930, verticalM: 980, duration: "4–6 t", grade: 4, aspect: "Ø", season: "jan–apr", hasGuide: true, teaser: "980 høydemeter fra rundkjøringa i Gullesfjordbotn: ryggen nordover vest for botn, den bratte renna til platået — og traversen til en topp uten én slak side: fire bratte nedkjøringer, og øks og stegjern i sekken." },
  { slug: "snotindan", name: "Snøtindan", region: "Harstad", lat: 68.54343, lng: 15.61609, summitM: 996, verticalM: 1550, duration: "7–9 t", grade: 4, aspect: "Ø", season: "jan–apr", hasGuide: true, teaser: "1550 høydemeter fra Løbergsbukta for en 996-topp: midt i Løbergsdalen mellom utløpssonene, over Løbergskaret, mellom vatna — og topphenget på 30–40 grader til slutt." },
  { slug: "fiskefjordtindan", name: "Fiskefjordtindan", region: "Harstad", lat: 68.53218, lng: 16.01129, summitM: 965, verticalM: 1080, duration: "5–7 t", grade: 3, aspect: "SV", season: "jan–apr", hasGuide: true, teaser: "1080 høydemeter fra Kanstadbotn: sommerstien, ryggen mellom Kobbedalsvatna — og den eksponerte austryggen til slutt, med øks og stegjern i sekken og en austside som måler 67 grader der den er brattest." },
  { slug: "moysalen", name: "Møysalen", region: "Vesterålen", lat: 68.52598, lng: 15.45215, summitM: 1264, verticalM: 1600, duration: "7–9 t", grade: 4, aspect: "S", season: "jan–mai", hasGuide: true, teaser: "1600 høydemeter fra E10 ved Litlvatnet: 355 av dem gir du fra deg underveis, 120 av dem ned til Grønnvatnet på 328." },
  { slug: "forselvtinden", name: "Forselvtinden", region: "Vesterålen", lat: 68.50934, lng: 15.50105, summitM: 907, verticalM: 1180, duration: "6–8 t", grade: 4, aspect: "S", season: "feb–apr", hasGuide: true, teaser: "1180 høgdemeter og 8,3 kilometer frå Lofast, over toppen av ein annan tur i katalogen: opp Lakselvtindan først, vestover til rett nord av høyde 790 — og sydryggen til slutt, med 296 høgdemeter gitt frå deg undervegs." },
  { slug: "middagsfjellet", name: "Middagsfjellet", region: "Harstad", lat: 68.50879, lng: 15.78279, summitM: 810, verticalM: 760, duration: "3–5 t", grade: 3, aspect: "N", season: "des–apr", hasGuide: true, teaser: "760 høydemeter fra rundkjøringa i Gullesfjordbotn — rundens korteste tur, og den slakeste traseen er hele poenget: lia vest for Tverrelva og Blåberget, med brattere skredterreng på alle kanter." },
  { slug: "strandtinden", name: "Strandtinden", region: "Harstad", lat: 68.50455, lng: 16.03441, summitM: 1076, verticalM: 1160, duration: "5–7 t", grade: 3, aspect: "N", season: "jan–jun", hasGuide: true, teaser: "1160 høydemeter fra E10 ved havet gjennom Heggedalen og opp vestryggen — Harstad-områdets store klassiker, og fjellet flest går der." },
  { slug: "jotind", name: "Jotind", region: "Harstad", lat: 68.50087, lng: 16.32663, summitM: 979, verticalM: 1050, duration: "5–7 t", grade: 4, aspect: "Ø", season: "feb–apr", hasGuide: true, teaser: "1050 høydemeter fra Mølnneset: ryggen over Spannbogen, henget før 600 der skiene gjerne bæres — og den smale toppryggen, med sommerruta på sørsida som utveien." },
  { slug: "forkledalstindan", name: "Forkledalstindan", region: "Vesterålen", lat: 68.49422, lng: 15.49073, summitM: 901, verticalM: 1020, duration: "4–6 t", grade: 4, aspect: "S", season: "feb–apr", hasGuide: true, teaser: "1020 høgdemeter frå E10 ved Litlvatnet: nordsida av høyde 462 og fjellsida opp til toppen på 700, der kildens skitur snur — og traversen vidare over fortoppen, med austsida som utvegen frå den vanskelege klatringa." },
  { slug: "lakselvtindan", name: "Lakselvtindan", region: "Vesterålen", lat: 68.4926, lng: 15.53235, summitM: 747, verticalM: 820, duration: "4–6 t", grade: 3, aspect: "SV", season: "feb–apr", hasGuide: true, teaser: "820 høgdemeter frå Møysalens parkering på E10: nordsida av Storvatnet, opp mellom Tverrelva og Lakselva, forbi høyde 258 — og ryggen aust for Lakselva til topps, det mildaste toppartiet i runden." },
  { slug: "siriskolten", name: "Siriskolten", region: "Harstad", lat: 68.47962, lng: 16.42142, summitM: 659, verticalM: 670, duration: "3–5 t", grade: 1, aspect: "N", season: "feb–apr", hasGuide: true, teaser: "670 høydemeter fra grustaket ved fv. 7548: sommerruta gjennom slakt terreng, bekken sør for 414-høgda — og vestover til toppen. Tjeldøyas innsteg, ideell for ferske, sier kilden." },
  { slug: "trollfjellet", name: "Trollfjellet", region: "Harstad", lat: 68.47689, lng: 16.27383, summitM: 1009, verticalM: 1030, duration: "5–7 t", grade: 2, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "1030 høydemeter fra Valvågen til Tjeldøyas eneste topp over 1000: vestbredden av Forsdalselva mellom furuene, aust for Kjerstadtinden — og ryggen til topps, med sol og slak fin kjøring hele veien hjem." },
  { slug: "sebortinden", name: "Sebortinden", region: "Vesterålen", lat: 68.47522, lng: 15.42604, summitM: 831, verticalM: 890, duration: "4–6 t", grade: 4, aspect: "N", season: "feb–apr", hasGuide: true, teaser: "890 høydemeter fra Møysalens parkering på E10: opp Forkledalen, sørsida av bekken — og traversen på austryggens flanke mot framtoppen, med øks og stegjern til sluttstøtet." },
  { slug: "helligtinden", name: "Helligtinden", region: "Harstad", lat: 68.46412, lng: 16.33452, summitM: 948, verticalM: 1030, duration: "4–6 t", grade: 3, aspect: "N", season: "feb–apr", hasGuide: true, teaser: "1030 høydemeter fra Breivikbotn: hyttefeltet ved Krokelva, Finnvatnet — og nordaustryggen av Litletinden til Helligtinden, med jevn kjøring på 10–20 grader hjem." },
  { slug: "kvasstinden", name: "Kvasstinden", region: "Vesterålen", lat: 68.43483, lng: 15.55651, summitM: 832, verticalM: 930, duration: "4–6 t", grade: 2, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "930 høgdemeter frå E10 ved Austerstraumen: myrene sørover, ned i Trolldalen nord for høyde 146 — og vestryggen til den luftige toppen, der 20–25 grader er regelen og øksa er for dei siste metrane." },
  { slug: "rombakstotta", name: "Rombakstøtta", region: "Narvik", lat: 68.43312, lng: 17.58324, summitM: 1231, verticalM: 1129, duration: "5–7 t", grade: 3, aspect: "SV", season: "feb–mai", hasGuide: true, teaser: "Narviks spisse landemerke — variert oppstigning og fin, vedvarende nedkjøring." },
  { slug: "beisfjordtotta", name: "Beisfjordtøtta", region: "Narvik", lat: 68.40588, lng: 17.57409, summitM: 1448, verticalM: 1430, duration: "6–8 t", grade: 3, aspect: "N", season: "feb–jun", hasGuide: true, teaser: "1430 høydemeter fra bommen over Djupvik: vannverksveien forbi Pumpvatnet, austsida av Forsnesvatnet på land — og skaret før ryggen sørover til fjellet med de mange hemmelighetene." },
  { slug: "pilan", name: "Pilan", region: "Lofoten", lat: 68.3688, lng: 14.66384, summitM: 826, verticalM: 850, duration: "3–5 t", grade: 3, aspect: "SØ", season: "feb–apr", hasGuide: true, teaser: "850 høydemeter fra Laupstad på nordsida av Austvågøya: dalen til vannet på 289, mot Morfjordskaret og den brede flanken — med et målt steg på 39 grader i toppkjegla." },
  { slug: "litletind", name: "Litletind", region: "Narvik", lat: 68.35964, lng: 17.33611, summitM: 1100, verticalM: 920, duration: "4–6 t", grade: 2, aspect: "NØ", season: "feb–mai", hasGuide: true, teaser: "920 høydemeter fra Nervatnet til fortoppen med byutsikten: myra sør for vannet, den glisne skogen og ryggen — Narvik og Rombaksfjorden under deg fra varden." },
  { slug: "geitgaljen", name: "Geitgaljen", region: "Lofoten", lat: 68.34434, lng: 14.81302, summitM: 1085, verticalM: 1070, duration: "4–6 t", grade: 4, aspect: "NV", season: "feb–apr", hasGuide: true, teaser: "1071 høydemeter fra Liland opp Lilandsdalen; renna fra 250 til 360 moh er 35 grader, og toppen krever stegjern." },
  { slug: "skjomtinden", name: "Skjomtinden", region: "Narvik", lat: 68.34341, lng: 17.35491, summitM: 1576, verticalM: 1490, duration: "6–8 t", grade: 4, aspect: "N", season: "feb–mai", hasGuide: true, teaser: "1490 høydemeter fra Nervatnet i Håkvikdalen til Den sovende dronning: forsenkningen rundt Litletind, ryggen mot Dronninga, traversen på vestsidene — og snørenna opp på eggen. Isøks og stegjern i sekken." },
  { slug: "torskmannen", name: "Torskmannen", region: "Lofoten", lat: 68.3368, lng: 14.60386, summitM: 755, verticalM: 750, duration: "3–5 t", grade: 3, aspect: "SØ", season: "jan–apr", hasGuide: true, teaser: "750 høydemeter fra Kvitfossen kraftstasjon i Vestpollen: dalen der snøen ligger skjermet, vannet i forsenkinga og skaret til høyre for toppen — og ryggen den siste biten." },
  { slug: "rundfjellet", name: "Rundfjellet", region: "Lofoten", lat: 68.2894, lng: 14.56524, summitM: 803, verticalM: 890, duration: "4–6 t", grade: 2, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "890 høydemeter fra havet ved Vatterfjordpollen: langs nordsida av pollen, opp på sørryggen og ryggtoppen hele veien — Svolværs nærmeste klassiker, med varianter til alle kanter." },
  { slug: "kleppstadheia", name: "Kleppstadheia", region: "Lofoten", lat: 68.26826, lng: 14.31161, summitM: 534, verticalM: 520, duration: "2–4 t", grade: 1, aspect: "SV", season: "jan–apr", hasGuide: true, teaser: "520 høydemeter fra Kleppstadveien sør for Gimsøybrua: ryggen mot punkt 156 og den slake, breie flata til topps — turen kilden selv bruker som øving i sporvalg." },
  { slug: "varden-smaatindan", name: "Varden (Småtindan)", region: "Lofoten", lat: 68.23317, lng: 14.38794, summitM: 700, verticalM: 825, duration: "4–6 t", grade: 2, aspect: "Ø", season: "jan–apr", hasGuide: true, teaser: "825 høgdemeter frå Eidet ved Kabelvåg: lysløypa langs Karlsvatnet, over eidet mot Ørntindaksla og gjennom skaret vest for han, og austflanken til toppen av øygruppas mest gåtte skitur." },
  { slug: "himmeltindan", name: "Himmeltindan", region: "Lofoten", lat: 68.22101, lng: 13.57307, summitM: 956, verticalM: 980, duration: "4–6 t", grade: 3, aspect: "Ø", season: "feb–apr", hasGuide: true, teaser: "Vestvågøys høyeste, med alpint preg og linjer rett mot Nordishavet." },
  { slug: "gangnesaksla", name: "Gangnesaksla", region: "Narvik", lat: 68.20105, lng: 17.26504, summitM: 1318, verticalM: 1310, duration: "5–7 t", grade: 3, aspect: "S", season: "feb–mai", hasGuide: true, teaser: "1310 høydemeter fra kraftstasjonen i Sørskjomen: anleggsveien langs Vesterskarelva, dammen ved tregrensa og hylla på 800 — med Frostisen i utsikten og Gangnesrenna under kanten." },
  { slug: "justadtinden", name: "Justadtinden", region: "Lofoten", lat: 68.18216, lng: 13.80369, summitM: 736, verticalM: 730, duration: "3–5 t", grade: 2, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "730 høydemeter fra gården Justad ved fv. 815: lia, ryggen over Skjærheia og det leikne toppartiet — Vestvågøys høyeste østside, med Vågakallen og Henningsvær under deg." },
  { slug: "stornappstinden", name: "Stornappstinden", region: "Lofoten", lat: 68.1441, lng: 13.41493, summitM: 740, verticalM: 680, duration: "3–5 t", grade: 2, aspect: "N", season: "jan–apr", hasGuide: true, teaser: "Lofot-klassiker i overkommelig format — mye fjell for høydemeterne." },
  { slug: "midtitinden", name: "Midtitinden", region: "Bodø", lat: 67.34238, lng: 15.00416, summitM: 1060, verticalM: 1050, duration: "4–6 t", grade: 2, aspect: "SØ", season: "jan–apr", hasGuide: true, teaser: "1050 høgdemeter frå havnivå ved Sagelva: gjennom hyttefeltet, rampene mot Innertinden, militærløypemerkinga vestover og ryggane til topps." },
  { slug: "sandhornet", name: "Sandhornet", region: "Bodø", lat: 67.11124, lng: 14.06789, summitM: 993, verticalM: 1020, duration: "4–6 t", grade: 2, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "1020 høgdemeter frå fjæra på Horsdal: stien langs sjøen, trappene til Stjerndalen, og slake rygger til varden på øyfjellet over Saltfjorden." },
  { slug: "tortenviktinden", name: "Tortenviktinden", region: "Helgeland", lat: 66.3421, lng: 13.23387, summitM: 1028, verticalM: 1020, duration: "4–6 t", grade: 2, aspect: "SØ", season: "feb–mai", hasGuide: true, teaser: "1023 høgdemeter frå Neset ved Flostrand: rett opp gjennom skogen, vestover på rabbane over det ulendte flatpartiet og opp den slake helninga til utsikta over Helgelandskysten." },
  { slug: "tomskjevelen", name: "Tomskjevelen", region: "Helgeland", lat: 66.27901, lng: 12.84655, summitM: 922, verticalM: 950, duration: "4–6 t", grade: 2, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "950 høgdemeter frå åkeren ved Forsland på Tomma: stien til Forslandsvatnet, rundt tjernet på land, og den nordvestgåande ryggen heilt til topps på øyfjellet Fri Flyt kallar ein av dei finaste toppane på Helgelandskysten." },
  { slug: "lukttinden", name: "Lukttinden", region: "Helgeland", lat: 65.99015, lng: 13.54443, summitM: 1348, verticalM: 1130, duration: "4–6 t", grade: 2, aspect: "NV", season: "apr–jun", hasGuide: true, teaser: "1129 høgdemeter frå garden på Kammen: traktorvegen, skogen mot bekken mellom Nordtinden og Lukttinden, og den slake ryggen opp til Vefsns mest markerte topp." },
  { slug: "vassfjellet", name: "Vassfjellet", region: "Trøndelag", lat: 63.26205, lng: 10.35659, summitM: 711, verticalM: 560, duration: "3–5 t", grade: 1, aspect: "V", season: "des–apr", hasGuide: true, teaser: "560 høydemeter fra Markavollen forbi Vassfjellhytta — den nærmeste toppturen til Trondheim, i løype hele vegen." },
  { slug: "krakfjellet", name: "Kråkfjellet", region: "Trøndelag", lat: 63.16336, lng: 10.63219, summitM: 815, verticalM: 470, duration: "4–6 t", grade: 2, aspect: "S", season: "des–apr", hasGuide: true, teaser: "Kommunetoppen i Trondheim: 470 høydemeter og ti kilometer fra Håen over Kråklivollen og Rundtjønnin." },
  { slug: "rensfjellet", name: "Rensfjellet", region: "Trøndelag", lat: 63.14219, lng: 10.72186, summitM: 942, verticalM: 700, duration: "5–7 t", grade: 2, aspect: "V", season: "des–apr", hasGuide: true, teaser: "700 høydemeter og elleve kilometer fra Håen over Rundtjønnin og Oksdalen til Melhus' høyeste punkt." },
  { slug: "snota", name: "Snota", region: "Trollheimen", lat: 62.84778, lng: 9.09428, summitM: 1668, verticalM: 1270, duration: "6–8 t", grade: 3, aspect: "Ø", season: "feb–mai", hasGuide: true, teaser: "1270 høydemeter fra Gråhaugen over Svartvatnet og rundt Litj-Snota til det høyeste fjellet nord i Trollheimen." },
  { slug: "storbekkhoa", name: "Storbekkhøa", region: "Trollheimen", lat: 62.73022, lng: 9.08038, summitM: 1504, verticalM: 890, duration: "4–6 t", grade: 2, aspect: "S", season: "des–mai", hasGuide: true, teaser: "890 høydemeter fra Storli opp Storbekkdalen og gjennom skaret vest for den bratte sørøstveggen." },
  { slug: "okla", name: "Okla", region: "Trollheimen", lat: 62.68955, lng: 9.26225, summitM: 1582, verticalM: 1020, duration: "4–6 t", grade: 2, aspect: "S", season: "des–apr", hasGuide: true, teaser: "1020 høydemeter fra Dalen i Storlidalen opp til Snydda — varden på toppen av Okla-massivet." },
  { slug: "storhornet", name: "Storhornet", region: "Trollheimen", lat: 62.64779, lng: 9.39918, summitM: 1589, verticalM: 940, duration: "4–6 t", grade: 2, aspect: "SØ", season: "des–mai", hasGuide: true, teaser: "940 høydemeter på merket vinterløype fra Bree gjennom Hornlia til steinbua på Oppdals mest besøkte topp." },
  { slug: "kirketaket", name: "Kirketaket", region: "Romsdal", lat: 62.61158, lng: 7.90672, summitM: 1439, verticalM: 1270, duration: "5–6 t", grade: 2, aspect: "SV", season: "des–mai", hasGuide: true, teaser: "Norges kanskje mest populære topptur: bred rygg, trygge linjevalg, lang sesong." },
  { slug: "skarven", name: "Skarven", region: "Romsdal", lat: 62.60775, lng: 7.60201, summitM: 1048, verticalM: 740, duration: "3–5 t", grade: 2, aspect: "SØ", season: "des–apr", hasGuide: true, teaser: "740 høydemeter fra bomvegen i Skorgedalen til en av Romsdalens store klassikere: myra ved Kjerringhaugen og Skorgedalsbu, sør for topp 588, og ryggen over den sørlige fortoppen til fjordutsikten på varden." },
  { slug: "mjolvafjellet", name: "Mjølvafjellet", region: "Romsdal", lat: 62.54172, lng: 7.76405, summitM: 1215, verticalM: 1220, duration: "5–7 t", grade: 2, aspect: "N", season: "jan–apr", hasGuide: true, teaser: "1220 høydemeter fra fjorden: traktorvegen fra Isfjorden stadion, skogen under Litlehesten, over Steinselva og den slake ryggen om Høgnosa — så sørover til toppen som henger over Romsdalen." },
  { slug: "blanebba", name: "Blånebba", region: "Romsdal", lat: 62.52627, lng: 7.79275, summitM: 1317, verticalM: 930, duration: "4–6 t", grade: 3, aspect: "NØ", season: "mar–mai", hasGuide: true, teaser: "930 høydemeter fra Venjesdalssetra til kanten som ser rett ned i Romsdalen: Romsdalseggen-merkinga langs Tverrelva, flata under Storhesten, nordøstflanken til skaret på 1245 — og hovedryggen østover til varden." },
  { slug: "ospetinden", name: "Øspetinden", region: "Romsdal", lat: 62.51586, lng: 7.25081, summitM: 1228, verticalM: 1060, duration: "5–7 t", grade: 3, aspect: "Ø", season: "des–mai", hasGuide: true, teaser: "1060 høydemeter fra bomkassa på Venås: setervegen til Venåssetra, myra over Stavvasselva, den store østvendte botnen — og nordøstryggen til pyramiden innerst i Måndalen." },
  { slug: "middagstinden", name: "Middagstinden", region: "Romsdal", lat: 62.46024, lng: 7.44099, summitM: 1568, verticalM: 1310, duration: "5–7 t", grade: 4, aspect: "V", season: "jan–apr", hasGuide: true, teaser: "1310 høydemeter fra Herdslan i Innfjorden: vegen langs Berillvatnet, bekkedalen til skaret ved Tindevatnet — og en ofte avblåst egg med ski på sekken før den vestvendte toppflanken." },
  { slug: "auskjeret", name: "Auskjeret", region: "Sunnmøre", lat: 62.37746, lng: 6.77458, summitM: 1203, verticalM: 870, duration: "3–5 t", grade: 2, aspect: "SØ", season: "des–apr", hasGuide: true, teaser: "870 høgdemeter frå Fausaskiftet i jamn stigning nordover — heilårsopen veg og moderate hellingar." },
  { slug: "snohetta", name: "Snøhetta", region: "Dovrefjell", lat: 62.31992, lng: 9.26747, summitM: 2286, verticalM: 820, duration: "5–7 t", grade: 2, aspect: "Ø", season: "apr–jun", hasGuide: true, teaser: "Storslått og luftig, men overraskende snill — når Snøheimvegen åpner." },
  { slug: "jonshornet", name: "Jønshornet", region: "Sunnmøre", lat: 62.31695, lng: 6.33395, summitM: 1417, verticalM: 1430, duration: "6–8 t", grade: 4, aspect: "N", season: "feb–mai", hasGuide: true, teaser: "1430 høgdemeter frå Vollane over Rametinden, og dei siste hundre på smal egg til varden på Ramoen." },
  { slug: "ytstevasshornet", name: "Ytstevasshornet", region: "Sunnmøre", lat: 62.28014, lng: 6.73548, summitM: 1331, verticalM: 830, duration: "3–5 t", grade: 3, aspect: "Ø", season: "jan–mai", hasGuide: true, teaser: "830 høgdemeter frå Svartevatnet: bratt opp Vassdalen til vatna på 950 moh, så nordvest mot ein smal og skavlete topprygg." },
  { slug: "rana", name: "Råna", region: "Sunnmøre", lat: 62.27554, lng: 6.57479, summitM: 1587, verticalM: 1600, duration: "7–9 t", grade: 3, aspect: "SØ", season: "mars–mai", hasGuide: true, teaser: "1600 høgdemeter frå Urkegjerdet ved fjorden: inn dalen til Nordkopen, bratt opp på egga og nordover den breie toppryggen." },
  { slug: "kolastinden", name: "Kolåstinden", region: "Sunnmøre", lat: 62.25886, lng: 6.31102, summitM: 1432, verticalM: 1120, duration: "5–7 t", grade: 3, aspect: "N", season: "feb–mai", hasGuide: true, teaser: "Alpin klassiker fra Standaldalen med velkjent renne og storslått finish." },
  { slug: "vassdalstinden", name: "Vassdalstinden", region: "Sunnmøre", lat: 62.24405, lng: 6.18966, summitM: 1278, verticalM: 1210, duration: "5–7 t", grade: 3, aspect: "Ø", season: "feb–mai", hasGuide: true, teaser: "1210 høgdemeter frå Nupen: seterveg til Vallasætra, kneiken opp i Bukkedalen og ein lang flanke til topps." },
  { slug: "saudehornet", name: "Saudehornet", region: "Sunnmøre", lat: 62.23578, lng: 6.14246, summitM: 1303, verticalM: 1160, duration: "4–6 t", grade: 3, aspect: "SV", season: "jan–mai", hasGuide: true, teaser: "1157 høgdemeter frå vassverket i Ørsta, og ryggkammen held rundt 32° i snitt dei siste 170, med det brattaste på 37." },
  { slug: "slogen", name: "Slogen", region: "Sunnmøre", lat: 62.20818, lng: 6.67306, summitM: 1564, verticalM: 1535, duration: "6–8 t", grade: 4, aspect: "V", season: "mar–mai", hasGuide: true, teaser: "Sunnmørsalpenes dronning — en alvorlig tur for erfarne, i riktig vindu." },
  { slug: "torvloysa", name: "Torvløysa", region: "Sunnmøre", lat: 62.1834, lng: 7.28026, summitM: 1851, verticalM: 1460, duration: "7–9 t", grade: 2, aspect: "N", season: "mars–mai", hasGuide: true, teaser: "1460 høgdemeter og ti kilometer frå Hatlestad over Rellingsætra og Daurmålsfjellet, mest slak rygg." },
  { slug: "skarene", name: "Skårene", region: "Sunnmøre", lat: 62.17982, lng: 7.19977, summitM: 1830, verticalM: 1220, duration: "5–7 t", grade: 3, aspect: "S", season: "mars–mai", hasGuide: true, teaser: "1220 høgdemeter frå Korsmyra opp Gråsteindalen og den store snøflanken til ein av dei høgaste toppane over Eidsdal." },
  { slug: "melshornet", name: "Melshornet", region: "Sunnmøre", lat: 62.17381, lng: 6.14287, summitM: 809, verticalM: 560, duration: "2–4 t", grade: 1, aspect: "SØ", season: "des–apr", hasGuide: true, teaser: "560 høgdemeter på preparert løype frå Helgatun — husfjellet som blir gått i mørket heile vinteren." },
  { slug: "jakta", name: "Jakta", region: "Sunnmøre", lat: 62.1711, lng: 6.61671, summitM: 1589, verticalM: 1560, duration: "6–8 t", grade: 3, aspect: "SØ", season: "feb–mai", hasGuide: true, teaser: "1560 høgdemeter frå Norang: slak stigning inn Konedalen, så ei 33-graders side opp på den smale toppryggen." },
  { slug: "skarasalen", name: "Skårasalen", region: "Sunnmøre", lat: 62.16566, lng: 6.48583, summitM: 1542, verticalM: 1452, duration: "6–8 t", grade: 3, aspect: "V", season: "jan–mai", hasGuide: true, teaser: "1438 høgdemeter frå bommen på Kvistadvegen, med det brattaste opp mot skaret på 1074 moh." },
  { slug: "kvitegga", name: "Kvitegga", region: "Sunnmøre", lat: 62.0948, lng: 6.7022, summitM: 1700, verticalM: 1480, duration: "6–8 t", grade: 3, aspect: "Ø", season: "mars–mai", hasGuide: true, teaser: "1480 høgdemeter frå Nibbedalen gjennom Snødalen og over Brattbakken til det høgste fjellet i midtre Sunnmørsalpane." },
  { slug: "hornindalsrokken", name: "Hornindalsrokken", region: "Sunnmøre", lat: 62.07148, lng: 6.65766, summitM: 1527, verticalM: 1470, duration: "6–8 t", grade: 4, aspect: "Ø", season: "mars–mai", hasGuide: true, teaser: "1470 høgdemeter frå Langøylia over Aksla, Trollaksla og Sætrenibba; dei siste 103 går på utsett rygg." },
  { slug: "sunndalsnipa", name: "Sunndalsnipa", region: "Sunnmøre", lat: 62.01816, lng: 6.32162, summitM: 1395, verticalM: 990, duration: "4–6 t", grade: 2, aspect: "S", season: "des–apr", hasGuide: true, teaser: "990 høgdemeter frå Grøndalsvatnet opp søraustryggen, og ein kilometer flatt platå fram til varden." },
  { slug: "eidskyrkja", name: "Eidskyrkja", region: "Sunnmøre", lat: 62.01709, lng: 6.2624, summitM: 1482, verticalM: 1120, duration: "4–6 t", grade: 3, aspect: "N", season: "mars–mai", hasGuide: true, teaser: "1120 høgdemeter frå Skinnviksætra opp Blåbreen: 25 grader nedst på breen og eit vidt toppplatå øvst." },
  { slug: "rondslottet", name: "Rondslottet", region: "Rondane", lat: 61.9149, lng: 9.8512, summitM: 2178, verticalM: 1280, duration: "6–8 t", grade: 2, aspect: "S", season: "mar–mai", hasGuide: true, teaser: "Rondanes høyeste: rolig høyfjellsterreng og stabil vårsesong." },
  { slug: "glitregga", name: "Glitregga", region: "Nordfjord", lat: 61.90741, lng: 6.37278, summitM: 1297, verticalM: 900, duration: "4–6 t", grade: 2, aspect: "S", season: "des–apr", hasGuide: true, teaser: "900 høgdemeter frå idrettsanlegget i Randabygd, sørvend og slak heile vegen opp." },
  { slug: "storronden", name: "Storronden", region: "Rondane", lat: 61.8917, lng: 9.86198, summitM: 2139, verticalM: 1140, duration: "6–8 t", grade: 2, aspect: "SV", season: "mars–mai", hasGuide: true, teaser: "1140 høydemeter fra Spranget: seks kilometer innmarsj til Rondvassbu, så 2,6 km jevn vestrygg fra stidelet på 1440 moh." },
  { slug: "skala", name: "Skåla", region: "Nordfjord", lat: 61.86923, lng: 6.97251, summitM: 1848, verticalM: 1820, duration: "6–8 t", grade: 3, aspect: "SV", season: "mar–jun", hasGuide: true, teaser: "1848 sammenhengende høydemeter fra fjorden i Loen — en av landets lengste nedkjøringer." },
  { slug: "skarsteinfjellet", name: "Skarsteinsfjellet", region: "Nordfjord", lat: 61.83055, lng: 6.73533, summitM: 1567, verticalM: 1220, duration: "5–7 t", grade: 2, aspect: "V", season: "jan–apr", hasGuide: true, teaser: "1220 høgdemeter opp ein jamn rygg over Innvikdalen — heile ruta i terreng under 30 grader." },
  { slug: "lodalskapa", name: "Lodalskåpa", region: "Nordfjord", lat: 61.79051, lng: 7.20475, summitM: 2082, verticalM: 1520, duration: "7–9 t", grade: 4, aspect: "V", season: "mai–jun", hasGuide: true, teaser: "1520 høgdemeter frå Bødalssætra over Kåpevatnet og Bohrsbreen til det einaste 2000-metersfjellet i Nordfjord." },
  { slug: "snonipa", name: "Snønipa", region: "Sunnfjord", lat: 61.67808, lng: 6.69055, summitM: 1827, verticalM: 1490, duration: "7–9 t", grade: 3, aspect: "SØ", season: "feb–mai", hasGuide: true, teaser: "1490 høgdemeter opp Haugadalen og midt i brefallet på Haugabreen til det høgste fjellet i Sunnfjord." },
  { slug: "glittertinden", name: "Glittertinden", region: "Jotunheimen", lat: 61.65138, lng: 8.5575, summitM: 2451, verticalM: 1228, duration: "7–9 t", grade: 3, aspect: "SØ", season: "juni–juli", hasGuide: true, teaser: "13,3 km og 1228 høydemeter fra Veodalen: 7 km flat innmarsj til Glitterheim, så jevn stigning øst for Glitterbrean." },
  { slug: "galdhopiggen", name: "Galdhøpiggen", region: "Jotunheimen", lat: 61.63644, lng: 8.31243, summitM: 2469, verticalM: 642, duration: "6–8 t", grade: 3, aspect: "N", season: "apr–jun", hasGuide: true, teaser: "Norges tak på ski — bre, tau og stor høyde; vanligvis gått fra Juvasshytta." },
  { slug: "steindalsnosi", name: "Steindalsnosi", region: "Sogn", lat: 61.52696, lng: 7.90076, summitM: 2025, verticalM: 760, duration: "3–5 t", grade: 1, aspect: "S", season: "apr–jun", hasGuide: true, teaser: "2000-meter for de fleste: kort, slak og solvendt fra Sognefjellsveien." },
  { slug: "besshoe", name: "Besshø", region: "Jotunheimen", lat: 61.51791, lng: 8.68712, summitM: 2257, verticalM: 1328, duration: "6–8 t", grade: 3, aspect: "Ø", season: "mars–mai", hasGuide: true, teaser: "1328 høydemeter fra Bessheim: tre og en halv kilometer langs Bessvatnet før Grotådalen, og til slutt den slake austryggen over Brue." },
  { slug: "fanaraken", name: "Fanaråken", region: "Sogn", lat: 61.51669, lng: 7.90825, summitM: 2068, verticalM: 780, duration: "5–7 t", grade: 2, aspect: "N", season: "apr–jun", hasGuide: true, teaser: "Høyfjellstur fra Sognefjellet med breutsikt og pålitelig vårsnø." },
  { slug: "kvamshesten", name: "Kvamshesten", region: "Sunnfjord", lat: 61.40141, lng: 5.62732, summitM: 1209, verticalM: 840, duration: "4–6 t", grade: 3, aspect: "N", season: "des–mai", hasGuide: true, teaser: "840 høgdemeter frå Rytnavegen forbi Skaravatnet og Grunnevatnet, med ei 36-graders skål til slutt." },
  { slug: "rasletinden", name: "Rasletinden", region: "Jotunheimen", lat: 61.39514, lng: 8.69944, summitM: 2104, verticalM: 778, duration: "4–6 t", grade: 2, aspect: "Ø", season: "apr–mai", hasGuide: true, teaser: "778 høydemeter og 7,2 km fra Valdresflye: flatt de første 2,2 km, så en kneik til 1530 moh og slak rygg østfra mot toppen." },
  { slug: "banseterkampen", name: "Bånsæterkampen", region: "Ringebufjellet", lat: 61.39144, lng: 10.10642, summitM: 1196, verticalM: 341, duration: "2–4 t", grade: 2, aspect: "NØ", season: "jan–apr", hasGuide: true, teaser: "330 høydemeter fra Bånsetra opp på en fjellrygg med stup mot sør — Kvitfjells nærmeste fjell, tvers over Lågen." },
  { slug: "molden", name: "Molden", region: "Sogn", lat: 61.34417, lng: 7.31973, summitM: 1120, verticalM: 620, duration: "2–4 t", grade: 1, aspect: "SV", season: "feb–apr", hasGuide: true, teaser: "620 høgdemeter frå Mollandsmarki opp sørvestryggen, med Lustrafjorden under seg heile vegen." },
  { slug: "synshorn", name: "Synshorn", region: "Valdres", lat: 61.34011, lng: 8.79727, summitM: 1475, verticalM: 420, duration: "2–3 t", grade: 1, aspect: "Ø", season: "feb–mai", hasGuide: true, teaser: "Kort og trygg tur fra Valdresflye — perfekt førstetur og værvindu-tur." },
  { slug: "togga", name: "Togga", region: "Sogn", lat: 61.33505, lng: 6.89289, summitM: 1204, verticalM: 780, duration: "3–5 t", grade: 3, aspect: "SØ", season: "des–mars", hasGuide: true, teaser: "780 høgdemeter rett frå toppturparkeringa på Brandhaugane: søraustryggen gjennom skogen, flata ved Orraleiken, og siste stigninga til varden." },
  { slug: "bitihorn", name: "Bitihorn", region: "Valdres", lat: 61.29435, lng: 8.79947, summitM: 1607, verticalM: 550, duration: "2–4 t", grade: 1, aspect: "S", season: "feb–mai", hasGuide: true, teaser: "Markert horn med enkel normalrute og fin utsikt over Bygdin." },
  { slug: "ulvsjoberget", name: "Ulvsjøberget", region: "Trysil", lat: 61.26561, lng: 12.018, summitM: 854, verticalM: 300, duration: "1–3 t", grade: 2, aspect: "SØ", season: "jan–apr", hasGuide: true, teaser: "300 høydemeter fra Vestby opp gjennom skogen til det åpne fjellet — den høyeste toppen i Trysil utenfor alpinanlegget." },
  { slug: "nevelfjell", name: "Nevelfjell", region: "Øyerfjellet", lat: 61.20491, lng: 10.56762, summitM: 1090, verticalM: 270, duration: "2–4 t", grade: 1, aspect: "Ø", season: "des–apr", hasGuide: true, teaser: "270 høydemeter fra Nordseter over Nevelåsen til Lillehammerfjellets mest besøkte topp, med åpen bu og siktskive på 1089." },
  { slug: "slettind", name: "Slettind", region: "Hemsedal", lat: 60.96896, lng: 8.18399, summitM: 1592, verticalM: 470, duration: "2–4 t", grade: 1, aspect: "NV", season: "jan–mai", hasGuide: true, teaser: "470 høgdemeter frå rv 52 ved Eldrevatn opp ei jamn 20–25-graders flanke — nybegynnartoppen på Hemsedalsfjellet." },
  { slug: "kyrkjebonosi", name: "Kyrkjebønosi", region: "Hemsedal", lat: 60.90555, lng: 8.55601, summitM: 1670, verticalM: 1000, duration: "4–6 t", grade: 3, aspect: "V", season: "feb–mai", hasGuide: true, teaser: "1000 høgdemeter frå grustaket ved Kyrkjebøen over den første toppen på 1610 og nordover den lange, flate ryggen." },
  { slug: "nibbi", name: "Nibbi", region: "Hemsedal", lat: 60.88661, lng: 8.6501, summitM: 1740, verticalM: 800, duration: "3–5 t", grade: 2, aspect: "S", season: "feb–mai", hasGuide: true, teaser: "800 høgdemeter frå Lykkjastølen vest for fossen og opp dalen — Hemsedals mest gåtte vårtopp." },
  { slug: "raskarfjellet", name: "Råskarfjellet", region: "Hemsedal", lat: 60.88427, lng: 8.20901, summitM: 1610, verticalM: 680, duration: "3–5 t", grade: 2, aspect: "NØ", season: "feb–mai", hasGuide: true, teaser: "680 høgdemeter frå Sildegjerdet ved rv 52 opp bekkedalen — hemsedølenes eigen klassikar, kjend berre som «1609»." },
  { slug: "skogshorn", name: "Skogshorn", region: "Hemsedal", lat: 60.88148, lng: 8.69482, summitM: 1729, verticalM: 840, duration: "3–5 t", grade: 2, aspect: "Ø", season: "feb–mai", hasGuide: true, teaser: "836 høgdemeter frå Trefta opp den breie austryggen; brattaste måling er 28,5 grader." },
  { slug: "finnbufjellet", name: "Finnbufjellet", region: "Voss", lat: 60.88074, lng: 6.44081, summitM: 1357, verticalM: 620, duration: "3–5 t", grade: 2, aspect: "NØ", season: "jan–apr", hasGuide: true, teaser: "620 høgdemeter frå leirplassen på toppen av Halsabakkane: over Sendo-elva og opp ryggen aust for Finnbujuvet, dit skisesongen på Voss vert opna og avslutta." },
  { slug: "storehorn", name: "Storehorn", region: "Hemsedal", lat: 60.81506, lng: 8.59566, summitM: 1482, verticalM: 470, duration: "3–4 t", grade: 2, aspect: "Ø", season: "des–apr", hasGuide: true, teaser: "Hemsedals husfjell for topptur — kort vei fra bilen, mange linjevalg." },
  { slug: "storanosi", name: "Storanosi", region: "Voss", lat: 60.7663, lng: 6.62341, summitM: 1205, verticalM: 740, duration: "3–5 t", grade: 2, aspect: "NØ", season: "jan–apr", hasGuide: true, teaser: "740 høgdemeter frå Ljosno gjennom open bjørkeskog og ut på platået over Brandsetdalen." },
  { slug: "lonahorgi", name: "Lønahorgi", region: "Voss", lat: 60.69383, lng: 6.41489, summitM: 1412, verticalM: 1300, duration: "6–8 t", grade: 2, aspect: "NØ", season: "feb–april", hasGuide: true, teaser: "1300 høgdemeter frå Høyland via Bergsstølen og Breiming, med dei siste 107 opp nordryggen frå punkt 1305." },
  { slug: "vatnaknausen", name: "Vatnaknausen", region: "Voss", lat: 60.64948, lng: 6.649, summitM: 1302, verticalM: 980, duration: "5–7 t", grade: 2, aspect: "V", season: "jan–apr", hasGuide: true, teaser: "980 høgdemeter frå Tverrberg: bomvegen inn Budalen til Nyestølen, opp på eggi vest for Rjupetjørnane, og austover platået til utsikta over Voss." },
  { slug: "horndalsnuten", name: "Horndalsnuten", region: "Voss", lat: 60.64218, lng: 6.67655, summitM: 1462, verticalM: 1120, duration: "5–7 t", grade: 3, aspect: "N", season: "jan–apr", hasGuide: true, teaser: "1120 høgdemeter frå Skiple gjennom Horndalsbotnen, med den bratte kneika frå skuldra til slutt." },
  { slug: "folarskardnuten", name: "Folarskardnuten", region: "Hallingdal", lat: 60.60742, lng: 7.78251, summitM: 1932, verticalM: 997, duration: "6–8 t", grade: 3, aspect: "S", season: "mars–mai", hasGuide: true, teaser: "Over 13 km inn frå Haugastøl og 997 høgdemeter, med eit kort 29-graders trinn opp frå Folarskardet." },
  { slug: "prestholtskarvet", name: "Prestholtskarvet", region: "Geilo", lat: 60.55843, lng: 8.0126, summitM: 1860, verticalM: 960, duration: "6–8 t", grade: 3, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "Elleve kilometer og 960 høydemeter fra Havsdalen forbi Prestholtstølan og opp Prestholtskardet til Hallingskarvets sørskarv." },
  { slug: "gyranfisen", name: "Gyranfisen", region: "Vikerfjell", lat: 60.47203, lng: 9.89027, summitM: 1127, verticalM: 670, duration: "3–5 t", grade: 2, aspect: "Ø", season: "jan–apr", hasGuide: true, teaser: "670 høydemeter fra Vikerkoia over Svarttjernskollen, med 200 av dem gitt tilbake i søkket før Ringerikes høyeste punkt." },
  { slug: "oksen", name: "Oksen", region: "Hardanger", lat: 60.45983, lng: 6.68301, summitM: 1241, verticalM: 960, duration: "4–6 t", grade: 2, aspect: "SV", season: "jan–apr", hasGuide: true, teaser: "Fjordutsikt i alle retninger og jevn stigning fra Tjoflot." },
  { slug: "ustetind", name: "Ustetind", region: "Geilo", lat: 60.45856, lng: 8.0902, summitM: 1376, verticalM: 410, duration: "2–4 t", grade: 2, aspect: "N", season: "feb–mai", hasGuide: true, teaser: "410 høydemeter fra Ustaoset forbi Tindevatnet til varden fra 1899, med Hardangervidda i sør og Hallingskarvet i nord." },
  { slug: "skrott", name: "Skrott", region: "Kvamskogen", lat: 60.45804, lng: 6.14387, summitM: 1320, verticalM: 1070, duration: "4–6 t", grade: 3, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "1068 høgdemeter frå støls- og hyttetunet i Fitjadalen: gangbru over Kjølo, bratt skogsli til Håsete, skihytta på 1110 moh og skaret mellom Glynt og toppen." },
  { slug: "sata", name: "Såta", region: "Kvamskogen", lat: 60.43136, lng: 5.99001, summitM: 1260, verticalM: 900, duration: "4–6 t", grade: 3, aspect: "SV", season: "jan–apr", hasGuide: true, teaser: "895 høgdemeter frå den innarste parkeringa ved Eikedalen skisenter: seterveg, flat anmarsj inn Skeiskvanndalen, og bratt flanke opp i skaret nord for toppen registeret òg kallar Iendefjell." },
  { slug: "gullfjellstoppen", name: "Gullfjellstoppen", region: "Bergen", lat: 60.38756, lng: 5.59037, summitM: 987, verticalM: 840, duration: "5–7 t", grade: 2, aspect: "SV", season: "jan–apr", hasGuide: true, teaser: "839 høgdemeter frå vegenden ved Osavatnet, forbi Redningshytta og opp Middagsdalen til Bergens høgaste punkt." },
  { slug: "tveitakvitingen", name: "Tveitakvitingen", region: "Kvamskogen", lat: 60.3254, lng: 5.90858, summitM: 1299, verticalM: 1000, duration: "5–7 t", grade: 3, aspect: "NØ", season: "jan–apr", hasGuide: true, teaser: "995 høgdemeter og 8,6 km frå Furedalen alpinsenter: langrennsspora på Mødalsvegen til Mødal, bratte kliv forbi Gråskorvenuten og ein langstrakt rygg til varden." },
  { slug: "grafjell", name: "Gråfjell", region: "Norefjell", lat: 60.31831, lng: 9.39572, summitM: 1466, verticalM: 595, duration: "4–6 t", grade: 2, aspect: "S", season: "des–mars", hasGuide: true, teaser: "580 høydemeter og 7,8 km fra Tempelsetra forbi Istjenn og Donkelitjenn til Norefjells høyeste topp." },
  { slug: "vesoldo", name: "Vesoldo", region: "Hardanger", lat: 60.31237, lng: 6.09197, summitM: 1046, verticalM: 840, duration: "3–5 t", grade: 2, aspect: "SV", season: "feb–apr", hasGuide: true, teaser: "838 høgdemeter frå Byrkjenes, skog opp til Fadnastølen og open sørvestrygg over; nord- og vestsida av toppen fell 48–55°." },
  { slug: "ranten", name: "Ranten", region: "Norefjell", lat: 60.30259, lng: 9.41922, summitM: 1416, verticalM: 530, duration: "3–5 t", grade: 2, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "530 høydemeter fra Tempelseter om stikrysset på Raudmyra og vestover opp på den taggete ryggen Kittelsen malte som Soria Moria." },
  { slug: "hogevarde", name: "Høgevarde", region: "Norefjell", lat: 60.2972, lng: 9.46662, summitM: 1461, verticalM: 600, duration: "3–5 t", grade: 1, aspect: "SV", season: "jan–apr", hasGuide: true, teaser: "600 høydemeter fra Tempelseter opp den oppstakede løypa til DNT-hytta på 1397, og de siste 560 metrene ut på ryggen til sikteplata." },
  { slug: "gygrastolen", name: "Gygrastolen", region: "Hardanger", lat: 60.05949, lng: 6.16031, summitM: 1347, verticalM: 1270, duration: "5–7 t", grade: 3, aspect: "N", season: "feb–apr", hasGuide: true, teaser: "1270 høgdemeter frå fjorden i Ænes opp ryggen over Gygrastølvatnet, rett mot Folgefonna." },
  { slug: "juklavasstinden", name: "Juklavasstinden", region: "Hardanger", lat: 60.00853, lng: 6.13296, summitM: 1361, verticalM: 1340, duration: "6–8 t", grade: 3, aspect: "NV", season: "mars–mai", hasGuide: true, teaser: "1340 høgdemeter frå Myrdalsvatnet: opp ryggen, ned mot Møsetjørna og opp nordryggen til ein skavla topp." },
  { slug: "melderskin", name: "Melderskin", region: "Hardanger", lat: 60.00623, lng: 6.08261, summitM: 1426, verticalM: 1270, duration: "6–8 t", grade: 3, aspect: "V", season: "feb–mai", hasGuide: true, teaser: "Rosendalsalpenes storslåtte klassiker, fra sjøen til 1426 moh." },
  { slug: "englafjell", name: "Englafjell", region: "Hardanger", lat: 59.89637, lng: 5.87533, summitM: 1200, verticalM: 1240, duration: "6–8 t", grade: 3, aspect: "N", season: "jan–apr", hasGuide: true, teaser: "1240 høgdemeter frå Musland i Uskedalen: traktorveg og merkt sti, over dalen, opp til Såta og sørover den bratte ryggen — med skavlane mot Limomnen som følgje til topps." },
  { slug: "gaustatoppen", name: "Gaustatoppen", region: "Telemark", lat: 59.8542, lng: 8.64928, summitM: 1883, verticalM: 970, duration: "4–6 t", grade: 2, aspect: "NV", season: "des–mai", hasGuide: true, teaser: "Sør-Norges mest markante topp — ser du den, ser den deg." },
  { slug: "store-ble", name: "Store Ble", region: "Blefjell", lat: 59.80825, lng: 9.15349, summitM: 1343, verticalM: 670, duration: "4–6 t", grade: 2, aspect: "SØ", season: "jan–apr", hasGuide: true, teaser: "670 høydemeter fra Nordstulvatnet gjennom skogen og opp om Sigridsbu — utløpssonene ligger i Langedalen ved sida av." },
  { slug: "surloytenuten", name: "Surløytenuten", region: "Blefjell", lat: 59.79473, lng: 9.20603, summitM: 1097, verticalM: 460, duration: "3–5 t", grade: 2, aspect: "S", season: "jan–apr", hasGuide: true, teaser: "460 høydemeter fra Nordstul om Sudstul og Vassholet, og sørover det ytre høydedraget langs Surløyterinden til varden." },
  { slug: "styggemann", name: "Styggemann", region: "Skrim", lat: 59.52064, lng: 9.64361, summitM: 871, verticalM: 550, duration: "4–6 t", grade: 2, aspect: "SV", season: "jan–mars", hasGuide: true, teaser: "550 høydemeter og 9,6 km fra Ravalsjø om Sørmyrseter, med de siste 240 rett opp på Skrims høyeste topp." },
  { slug: "saebyggjenuten", name: "Sæbyggjenuten", region: "Setesdal", lat: 59.46181, lng: 7.62568, summitM: 1506, verticalM: 850, duration: "6–8 t", grade: 3, aspect: "V", season: "feb–apr", hasGuide: true, teaser: "850 høgdemeter og 11,3 km inn frå Berdalen over Tverrheiskara og Gjuvvatna; nordsida av toppen fell 42° og er ofte skavla." },
  { slug: "kjerag", name: "Kjerag", region: "Rogaland", lat: 59.01672, lng: 6.58762, summitM: 1124, verticalM: 620, duration: "4–6 t", grade: 2, aspect: "Ø", season: "mai–juni", hasGuide: true, teaser: "620 høgdemeter frå Øygardstøl om Langvassvegen og Kjeragplatået; brattaste 30 meter er 24,4 grader på ein vegsving, men Lysevegen opnar først i mai." },
];

export const REGIONS: string[] = [...new Set(TOURS.map((t) => t.region))];

export function getTour(slug: string): Tour | undefined {
  return TOURS.find((t) => t.slug === slug);
}

/** Turene i én region, eventuelt uten den man allerede står på.
 *
 *  Brukes av «flere turer i …» nederst i hver guide. Regionen er den eneste
 *  slektskapen datasettet faktisk kjenner — «lignende tur» ville vært en
 *  påstand om terreng vi ikke måler. */
export function toursInRegion(region: string, exclude?: string): Tour[] {
  return TOURS.filter((t) => t.region === region && t.slug !== exclude);
}

/** Turene gruppert på region, i den rekkefølgen `TOURS` står i — som er nord
 *  til sør, fra Lyngen til Gaustatoppen. Rekkefølgen er redaksjonell og skal
 *  overleve grupperinga; derfor `REGIONS` og ikke en sortert nøkkelliste. */
export function toursByRegion(): { region: string; tours: Tour[] }[] {
  return REGIONS.map((region) => ({ region, tours: toursInRegion(region) }));
}

/** Ankeret en region får på `/turer`: «Sunnmøre» → `sunnmore`.
 *
 *  Fragmentet havner i adressefeltet og i delte lenker, så det holdes til
 *  ASCII framfor å bli prosentkodet til `#Sunnm%C3%B8re`. */
export function regionAnchor(region: string): string {
  return region
    .toLowerCase()
    .replace(/æ/g, "ae")
    .replace(/ø/g, "o")
    .replace(/å/g, "a")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

/** Every documented way up a tour, the tour's own route first.
 *
 *  A peak can have more than one, and they are not variants of one line:
 *  Galdhøpiggen's two standard starts are 737 vertical metres apart. The first
 *  route is the one the tour's `verticalM` and `duration` describe. */
export function routesFor(t: Tour): readonly TourRoute[] {
  return ROUTES[t.slug] ?? [];
}

/** En rute uten geometrien: alt rutevelgeren i panelet viser. */
export type RouteMeta = Omit<TourRoute, "line">;

/** Rutene til hver tur, uten linjene.
 *
 *  Rutevelgeren på `/kart` viser navn, oppstigning, lengde og utgangspunkt — den
 *  har aldri hatt bruk for punktene. Å hente dem derfra kostet likevel hele
 *  `lib/routes` i nettleseren, fordi `routesFor` og geometrien bor i samme
 *  modul: rundt 240 kB terrengpunkter lastet ned og parset før lista til
 *  venstre kunne trykkes på.
 *
 *  Denne kjører på serveren og sendes inn som en prop, så det klienten får er
 *  det den viser. Linjene lastes fortsatt — de skal tegnes — men i Leaflet-bunten
 *  som uansett hentes for seg, og ikke foran alt annet. */
export function routeMeta(): Record<string, RouteMeta[]> {
  const out: Record<string, RouteMeta[]> = {};
  for (const tour of TOURS) {
    const routes = routesFor(tour);
    if (!routes.length) continue;
    out[tour.slug] = routes.map(({ id, name, trailhead, distanceM, gainM }) => ({
      id,
      name,
      trailhead,
      distanceM,
      gainM,
    }));
  }
  return out;
}

/** One route of a tour, by id. Falls back to the tour's own route when `id` is
 *  missing or unknown, so a stale `?rute=` in a shared link still draws. */
export function routeById(t: Tour, id?: string | null): TourRoute | null {
  const routes = routesFor(t);
  if (!routes.length) return null;
  return (id ? routes.find((r) => r.id === id) : undefined) ?? routes[0];
}

/** The detailed ascent line, trailhead first and summit last.
 *
 *  The geometry lives in `./routes` — a least-cost path solved over Kartverket's
 *  1 m terrain model through the corridor the route uses. Empty when a tour has
 *  no route yet, so callers should check before drawing. */
export function routeFor(t: Tour, id?: string | null): [number, number][] {
  const route = routeById(t, id);
  if (!route) return [];
  const out: [number, number][] = [];
  for (let i = 0; i < route.line.length; i += 3) {
    out.push([route.line[i], route.line[i + 1]]);
  }
  return out;
}

/** The same line with its terrain elevations, for the GPX track and the profile.
 *  `points[i]` and `elevations[i]` describe the same place. */
export function routeProfile(
  t: Tour,
  id?: string | null,
): {
  points: [number, number][];
  elevations: number[];
  distanceM: number;
  gainM: number;
  routeId: string;
  routeName: string;
  trailhead: string;
} | null {
  const route = routeById(t, id);
  if (!route) return null;
  const points: [number, number][] = [];
  const elevations: number[] = [];
  for (let i = 0; i < route.line.length; i += 3) {
    points.push([route.line[i], route.line[i + 1]]);
    elevations.push(route.line[i + 2]);
  }
  return {
    points,
    elevations,
    distanceM: route.distanceM,
    gainM: route.gainM,
    routeId: route.id,
    routeName: route.name,
    trailhead: route.trailhead,
  };
}
